services:
#    softgroup_final.example:
#        class: Softgroup\FinalBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    softgroup_final.admin.message:
        class: Softgroup\FinalBundle\Admin\MessageAdmin
        arguments: [~, Softgroup\FinalBundle\Entity\Message, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Message }
